package com.epam.jmp.protocols.avro.controllers;

import com.epam.jmp.protocols.avro.domain.UserRequest;
import com.epam.jmp.protocols.avro.producer.Sender;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(value = "/kafka")
public class KafkaController {

    private final Sender sender;

    @Autowired
    KafkaController(Sender sender) {
        this.sender = sender;
    }

    @PostMapping(value = "/v1/users")
    public void sendSchemaRegistryToKafkaTopic(@RequestBody UserRequest request) {
        com.epam.jmp.protocols.avro.example.User user = com.epam.jmp.protocols.avro.example.User.newBuilder()
                .setName(request.getName())
                .setFavoriteColor(request.getFavoriteColor())
                // uncommit after replacing User with generated by V2 avro schema
//                .setRegretColor(request.getRegretColor())
                .setId(request.getId())
                .build();
        this.sender.send(user);
    }

}
